--liquibase formatted sql

--changeset Jiri.Kriz1:1576501454269-1
CREATE TABLE ABILITY_SCORE (ID RAW(16) NOT NULL, ABILITY VARCHAR2(15 BYTE) NOT NULL, VALUE NUMBER(3, 0) NOT NULL, BONUS NUMBER(3, 0) NOT NULL, BEASTBLUEPRINT_ID RAW(16), PERSON_ID RAW(16), CONSTRAINT ABILITY_SCORE_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-2
CREATE TABLE ARMOR (ID RAW(16) NOT NULL, DEFENSE NUMBER(3, 0) NOT NULL, EQUIPPED NUMBER(1, 0) NOT NULL, CONSTRAINT ARMORY_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-3
CREATE TABLE ARMOR_BLUEPRINT (ID RAW(16) NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, PUBLIC_DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, WEIGHT NUMBER(6, 0) NOT NULL, DEFENSE NUMBER(3, 0) NOT NULL, PRIVATE_DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, CONSTRAINT ARMOR_BLUEPRINT_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-4
CREATE TABLE ARMOR_COVERAGE (BODY_SECTION VARCHAR2(25 BYTE) NOT NULL, ARMOR_ID RAW(16) NOT NULL, CONSTRAINT ARMOR_COVERAGE_PK PRIMARY KEY (BODY_SECTION, ARMOR_ID));

--changeset Jiri.Kriz1:1576501454269-5
CREATE TABLE ARMOR_COVERAGE_BLUEPRINT (BODY_SECTION VARCHAR2(25 BYTE) NOT NULL, ARMOR_BLUEPRINT_ID RAW(16) NOT NULL, CONSTRAINT ARMOR_COVERAGE_BLUEPRINT_PK PRIMARY KEY (BODY_SECTION, ARMOR_BLUEPRINT_ID));

--changeset Jiri.Kriz1:1576501454269-6
CREATE TABLE BEAST (ID RAW(16) NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, LIFE NUMBER(5, 0) NOT NULL, BEAST_SIZE VARCHAR2(2 BYTE) NOT NULL, BEASTBLUEPRINT_ID RAW(16) NOT NULL, DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, INVENTORY_ID RAW(16) NOT NULL, ATTACK NUMBER(3, 0) NOT NULL, HURT NUMBER(3, 0) NOT NULL, ACTIVE_DEFENSE NUMBER(3, 0) NOT NULL, PASSIVE_DEFENSE NUMBER(3, 0) NOT NULL, INITIATIVE_BASE NUMBER(3, 0) NOT NULL, CONSTRAINT BEAST_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-7
CREATE TABLE BEAST_BLUEPRINT (ID RAW(16) NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, SPECIES VARCHAR2(50 BYTE) NOT NULL, VIABILITY NUMBER(4, 0) NOT NULL, VIABILITYBONUS NUMBER(4, 0) NOT NULL, MANNA NUMBER(6, 0) NOT NULL, MOBILITY NUMBER(3, 0) NOT NULL, PUGNACITY NUMBER(3, 0) NOT NULL, PERSISTENCE NUMBER(3, 0) NOT NULL, TAMEABILITY NUMBER(3, 0) NOT NULL, TRAINED NUMBER(1, 0) NOT NULL, INVENTORY_ID RAW(16) NOT NULL, BEAST_ORIGIN VARCHAR2(50 BYTE) NOT NULL, DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, ATTACK NUMBER(3, 0) NOT NULL, HURT NUMBER(3, 0) NOT NULL, ACTIVE_DEFENSE NUMBER(3, 0) NOT NULL, PASSIVE_DEFENSE NUMBER(3, 0) NOT NULL, INITIATIVE_BASE NUMBER(3, 0) NOT NULL, CONSTRAINT BEAST_BLUEPRINT_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-8
CREATE TABLE BEAST_SIZE (CHARACTER_SIZE VARCHAR2(2 BYTE) NOT NULL, BEAST_BLUEPRINT_ID RAW(16) NOT NULL, CONSTRAINT BEAST_SIZE_PK PRIMARY KEY (CHARACTER_SIZE, BEAST_BLUEPRINT_ID));

--changeset Jiri.Kriz1:1576501454269-9
CREATE TABLE BEAST_VULNERABILITY (VULNERABILITY VARCHAR2(2 BYTE) NOT NULL, BEAST_BLUEPRINT_ID RAW(16) NOT NULL, CONSTRAINT BEAST_VULNERABILITY_PK PRIMARY KEY (VULNERABILITY, BEAST_BLUEPRINT_ID));

--changeset Jiri.Kriz1:1576501454269-10
CREATE TABLE COHERENCE (ID RAW(16) NOT NULL, PERSON_ID RAW(16) NOT NULL, COMMON_LEVELS NUMBER(3, 0) NOT NULL, WARRIOR_KNOWHOW_ID RAW(16) NOT NULL, CONSTRAINT COHERENCE_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-11
CREATE TABLE ENCOUNTER (NR_OF_ENCOUNTERS NUMBER(5, 0) NOT NULL, WARRIOR_KNOWHOW_ID RAW(16) NOT NULL, ID RAW(16) NOT NULL, BEAST_BLUEPRINT_ID RAW(16) NOT NULL, CONSTRAINT ENCOUNTER_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-12
CREATE TABLE EQUIPMENT (ID RAW(16) NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, WEIGHT NUMBER(6, 0) NOT NULL, STORAGE_UNIT_ID RAW(16), CONSTRAINT EQUIPMENT_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-13
CREATE TABLE GEMSTONE (ID RAW(16) NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, COLOR VARCHAR2(50 BYTE) NOT NULL, UNIT_PRICE FLOAT(22) NOT NULL, CONSTRAINT GEMSTONE_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-14
CREATE TABLE GOODS_BLUEPRINT (ID RAW(16) NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, PUBLIC_DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, PRIVATE_DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, WEIGHT NUMBER(6, 0) NOT NULL, ITEM_TYPE VARCHAR2(25 BYTE) NOT NULL, CONSTRAINT GOODS_BLUEPRINT_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-15
CREATE TABLE HT_ARMOR (ID RAW(255) NOT NULL);

--changeset Jiri.Kriz1:1576501454269-16
CREATE TABLE HT_EQUIPMENT (ID RAW(255) NOT NULL);

--changeset Jiri.Kriz1:1576501454269-17
CREATE TABLE HT_STORAGE_UNIT (ID RAW(255) NOT NULL);

--changeset Jiri.Kriz1:1576501454269-18
CREATE TABLE HT_TREASURE (ID RAW(255) NOT NULL);

--changeset Jiri.Kriz1:1576501454269-19
CREATE TABLE HT_WEAPON (ID RAW(255) NOT NULL);

--changeset Jiri.Kriz1:1576501454269-20
CREATE TABLE INVENTORY (ID RAW(16) NOT NULL, LIMIT_WEIGHT NUMBER(6, 0) NOT NULL, CONTENT_WEIGHT NUMBER(6, 0) NOT NULL, COIN_POUCH FLOAT(22) NOT NULL, BANK_VAULT FLOAT(22) NOT NULL, CONSTRAINT INVENTORY_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-21
CREATE TABLE LOCAL_PRICE (ID RAW(16) NOT NULL, PRICE FLOAT(22) NOT NULL, DEAL_LOCATION VARCHAR2(50 BYTE) NOT NULL, SHOP_ITEM_ID RAW(16) NOT NULL, CONSTRAINT LOCAL_PRICE_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-22
CREATE TABLE PERSON (ID RAW(16) NOT NULL, PERSONBLUEPRINT_ID RAW(16), NAME VARCHAR2(25 BYTE) NOT NULL, DESCRIPTION VARCHAR2(500 BYTE), PERSON_LEVEL NUMBER(3, 0) NOT NULL, EXP NUMBER(9, 0) NOT NULL, CURRENT_LIFE NUMBER(4, 0) NOT NULL, MAXIMAL_LIFE NUMBER(4, 0) NOT NULL, CURRENT_MANNA NUMBER(4, 0) NOT NULL, MAXIMAL_MANNA NUMBER(4, 0) NOT NULL, WEIGHT NUMBER(6, 0) NOT NULL, HEIGHT NUMBER(4, 0) NOT NULL, PROFESSION_KNOWHOW_ID RAW(16) NOT NULL, ATTACK NUMBER(3, 0) NOT NULL, HURT NUMBER(3, 0) NOT NULL, ACTIVE_DEFENSE NUMBER(3, 0) NOT NULL, PASSIVE_DEFENSE NUMBER(3, 0) NOT NULL, INITIATIVE_BASE NUMBER(3, 0) NOT NULL, INVENTORY_ID RAW(16) NOT NULL, RACE_ID RAW(16) NOT NULL, CONSTRAINT PERSON_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-23
CREATE TABLE PERSON_BLUEPRINT (ID RAW(16) NOT NULL, NAME VARCHAR2(25 BYTE) NOT NULL, DESCRIPTION VARCHAR2(250 BYTE), PERSON_LEVEL NUMBER(2, 0) NOT NULL, RACE_ID RAW(16) NOT NULL, PROFESSION VARCHAR2(25 BYTE) NOT NULL, INVENTORY_ID RAW(16) NOT NULL, CONSTRAINT PERSON_BLUEPRINT_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-24
CREATE TABLE PROFESSION_KNOWHOW (ID RAW(16) NOT NULL, PROFESSION VARCHAR2(50 BYTE) NOT NULL, PYROKINESIS_LEVEL_LEARNED NUMBER(3, 0) NOT NULL, TELEKINESIS_LEVEL_LEARNED NUMBER(3, 0) NOT NULL, TELEPATHY_LEVEL_LEARNED NUMBER(3, 0) NOT NULL, CONSTRAINT PROFESSION_KNOWHOW_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-25
CREATE TABLE RACE (ID RAW(16) NOT NULL, NAME VARCHAR2(25 BYTE) NOT NULL, DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, RACE_SIZE VARCHAR2(1 BYTE) NOT NULL, MIN_WEIGHT NUMBER(5, 0) NOT NULL, MAX_WEIGHT NUMBER(5, 0) NOT NULL, MIN_HEIGHT NUMBER(5, 0) NOT NULL, MAX_HEIGHT NUMBER(5, 0) NOT NULL, WEAPON_ID RAW(16) NOT NULL, STRENGTH_NR_OF_THROWS NUMBER(2, 0) NOT NULL, DEXTERITY_NR_OF_THROWS NUMBER(2, 0) NOT NULL, RESISTANCE_NR_OF_THROWS NUMBER(2, 0) NOT NULL, INTELLIGENCE_NR_OF_THROWS NUMBER(2, 0) NOT NULL, CHARISMA_NR_OF_THROWS NUMBER(2, 0) NOT NULL, STRENGTH_ABILITY_BASE NUMBER(2, 0) NOT NULL, DEXTERITY_ABILITY_BASE NUMBER(2, 0) NOT NULL, RESISTANCE_ABILITY_BASE NUMBER(2, 0) NOT NULL, INTELLIGENCE_ABILITY_BASE NUMBER(2, 0) NOT NULL, CHARISMA_ABILITY_BASE NUMBER(2, 0) NOT NULL, STRENGTH_ABILITY_CORRECTION NUMBER(2, 0) NOT NULL, DEXTERITY_ABILITY_CORRECTION NUMBER(2, 0) NOT NULL, RESISTANCE_ABILITY_CORRECTION NUMBER(2, 0) NOT NULL, INTELLIGENCE_ABILITY_CORRECTION NUMBER(2, 0) NOT NULL, CHARISMA_ABILITY_CORRECTION NUMBER(2, 0) NOT NULL, CONSTRAINT RACE_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-26
CREATE TABLE SHOP_ITEM (ID RAW(16) NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, ITEM_TYPE VARCHAR2(25 BYTE) NOT NULL, CONSTRAINT SHOP_ITEM_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-27
CREATE TABLE SKILL (ID RAW(16) NOT NULL, NAME VARCHAR2(25 BYTE) NOT NULL, DIFFICULTY VARCHAR2(25 BYTE) NOT NULL, ABILITY VARCHAR2(25 BYTE) NOT NULL, FULL_SUCCESS VARCHAR2(500 BYTE) NOT NULL, SUCCESS VARCHAR2(500 BYTE) NOT NULL, FAILURE VARCHAR2(500 BYTE) NOT NULL, FATAL_FAILURE VARCHAR2(500 BYTE) NOT NULL, CONSTRAINT SKILL_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-28
CREATE TABLE SKILL_KNOWHOW (ID RAW(16) NOT NULL, POINTS_TOTAL NUMBER(4, 0) NOT NULL, POINTS_FOR_NEXT_LEVEL NUMBER(4, 0) NOT NULL, SKILL_KNOWLEDGE VARCHAR2(25 BYTE) NOT NULL, SKILL RAW(16) NOT NULL, CONSTRAINT SKILL_KNOWHOW_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-29
CREATE TABLE SPELL (ID RAW(16) NOT NULL, NAME VARCHAR2(25 BYTE) NOT NULL, DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, MANNA_COST NUMBER(3, 0) NOT NULL, RANGE_OR_DIAMETER NUMBER(4, 0) NOT NULL, CONJURING NUMBER(4, 0) NOT NULL, DURATION NUMBER(4, 0) NOT NULL, CONSTRAINT SPELL_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-30
CREATE TABLE SPELLBOOK (ID RAW(16) NOT NULL, WIZARD_KNOWHOW_ID RAW(16) NOT NULL, SPELL_ID RAW(16) NOT NULL, CONSTRAINT SPELLBOOK_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-31
CREATE TABLE STORAGE_UNIT (ID RAW(16) NOT NULL, STORAGE_CAPACITY NUMBER(6, 0) NOT NULL, CONTENT_WEIGHT NUMBER(6, 0) NOT NULL, INVENTORY_ID RAW(16) NOT NULL, DEFAULT_STORAGE NUMBER(1, 0) NOT NULL, CONSTRAINT STORAGE_UNIT_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-32
CREATE TABLE TREASURE_BLUEPRINT (ID RAW(16) NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, PUBLIC_DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, PRIVATE_DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, STONE VARCHAR2(50 BYTE) NOT NULL, STONE_WEIGHT NUMBER(6, 0) NOT NULL, TREASURE_VALUE FLOAT(22) NOT NULL, METAL VARCHAR2(50 BYTE) NOT NULL, METAL_WEIGHT NUMBER(6, 0) NOT NULL, PRODUCT_QUALITY VARCHAR2(50 BYTE) NOT NULL, GEMSTONE_ID RAW(16) NOT NULL, CONSTRAINT TREASURE_BLUEPRINT_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-33
CREATE TABLE TREASURY (ID RAW(16) NOT NULL, NAME VARCHAR2(25 BYTE) NOT NULL, DESCRIPTION VARCHAR2(250 BYTE) NOT NULL, WEIGHT NUMBER, STORAGE_ID RAW(16), CONSTRAINT TREASURY_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-34
CREATE TABLE WEAPON (ID RAW(16) NOT NULL, ATTACK NUMBER(3, 0) NOT NULL, HURT NUMBER(3, 0) NOT NULL, DEFENSE NUMBER(3, 0) NOT NULL, MIN_MELEE_REACH NUMBER(2, 0) NOT NULL, MAX_MELEE_REACH NUMBER(2, 0) NOT NULL, EQUIPPED NUMBER(1, 0) NOT NULL, INITIATIVE_MODIFIER NUMBER(3, 0) NOT NULL, SHORT_RANGE_LIMIT NUMBER(6, 0) NOT NULL, MID_RANGE_LIMIT NUMBER(6, 0) NOT NULL, LONG_RANGE_LIMIT NUMBER(6, 0) NOT NULL, CONSTRAINT WEAPONRY_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-35
CREATE TABLE WEAPONTYPE_PROFICIENCY (ID RAW(16) NOT NULL, NR_OF_LEVELS_USED NUMBER(3, 0) NOT NULL, WARRIOR_KNOWHOW_ID RAW(16) NOT NULL, WEAPON_BLUEPRINT_ID RAW(16) NOT NULL, CONSTRAINT WEAPONTYPE_PROFICIENCY_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-36
CREATE TABLE WEAPON_BLUEPRINT (ID RAW(16) NOT NULL, NAME VARCHAR2(25 BYTE) NOT NULL, PUBLIC_DESCRIPTION VARCHAR2(250 BYTE) NOT NULL, WEIGHT NUMBER(6, 0) NOT NULL, ATTACK NUMBER(3, 0) NOT NULL, HURT NUMBER(3, 0) NOT NULL, DEFENSE NUMBER(3, 0) NOT NULL, INITIATIVE_MODIFIER NUMBER(3, 0) NOT NULL, SHORT_RANGE_LIMIT NUMBER(6, 0) NOT NULL, MID_RANGE_LIMIT NUMBER(6, 0) NOT NULL, LONG_RANGE_LIMIT NUMBER(6, 0) NOT NULL, MIN_MELEE_REACH NUMBER(2, 0) NOT NULL, MAX_MELEE_REACH NUMBER(2, 0) NOT NULL, PRIVATE_DESCRIPTION VARCHAR2(500 BYTE) NOT NULL, CONSTRAINT WEAPON_BLUEPRINT_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-37
CREATE TABLE WEAPON_PROFICIENCY (ID RAW(16) NOT NULL, EXPERIENCE_EARNED NUMBER(6, 0) NOT NULL, WARRIOR_KNOWHOW_ID RAW(16) NOT NULL, WEAPON_ID RAW(16) NOT NULL, CONSTRAINT WEAPON_PROFICIENCY_PK PRIMARY KEY (ID));

--changeset Jiri.Kriz1:1576501454269-38
CREATE TABLE WEAPON_TYPE (WEAPON_TYPE VARCHAR2(25 BYTE) NOT NULL, WEAPON_ID RAW(16) NOT NULL, CONSTRAINT WEAPON_TYPE_PK PRIMARY KEY (WEAPON_TYPE, WEAPON_ID));

--changeset Jiri.Kriz1:1576501454269-39
CREATE TABLE WEAPON_TYPE_BLUEPRINT (WEAPON_TYPE VARCHAR2(25 BYTE) NOT NULL, WEAPON_BLUEPRINT_ID RAW(16) NOT NULL, CONSTRAINT WEAPON_TYPE_BLUEPRINT_PK PRIMARY KEY (WEAPON_TYPE, WEAPON_BLUEPRINT_ID));

--changeset Jiri.Kriz1:1576501454269-40
ALTER TABLE ABILITY_SCORE ADD CONSTRAINT ABILITY_SCORE_BEAST_BLUEPRINT_ID_FK FOREIGN KEY (BEASTBLUEPRINT_ID) REFERENCES BEAST_BLUEPRINT (ID);

--changeset Jiri.Kriz1:1576501454269-41
ALTER TABLE ABILITY_SCORE ADD CONSTRAINT ABILITY_SCORE_PERSON_ID_FK FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID);

--changeset Jiri.Kriz1:1576501454269-42
ALTER TABLE ARMOR_COVERAGE ADD CONSTRAINT ARMOR_COVERAGE_ARMOR_ID_FK FOREIGN KEY (ARMOR_ID) REFERENCES ARMOR (ID);

--changeset Jiri.Kriz1:1576501454269-43
ALTER TABLE ARMOR_COVERAGE_BLUEPRINT ADD CONSTRAINT ARMOR_COVERAGE_BLUEPRINT_ARMOR_BLUEPRINT_ID_FK FOREIGN KEY (ARMOR_BLUEPRINT_ID) REFERENCES ARMOR_BLUEPRINT (ID);

--changeset Jiri.Kriz1:1576501454269-44
ALTER TABLE ARMOR ADD CONSTRAINT ARMOR_EQUIPMENT_ID_FK FOREIGN KEY (ID) REFERENCES EQUIPMENT (ID);

--changeset Jiri.Kriz1:1576501454269-45
ALTER TABLE BEAST ADD CONSTRAINT BEAST_BEAST_BLUEPRINT_ID_FK FOREIGN KEY (BEASTBLUEPRINT_ID) REFERENCES BEAST_BLUEPRINT (ID);

--changeset Jiri.Kriz1:1576501454269-46
ALTER TABLE BEAST_BLUEPRINT ADD CONSTRAINT BEAST_BLUEPRINT_INVENTORY_ID_FK FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY (ID);

--changeset Jiri.Kriz1:1576501454269-47
ALTER TABLE BEAST ADD CONSTRAINT BEAST_INVENTORY_ID_FK FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY (ID);

--changeset Jiri.Kriz1:1576501454269-48
ALTER TABLE BEAST_SIZE ADD CONSTRAINT BEAST_SIZE_BEAST_BLUEPRINT_ID_FK FOREIGN KEY (BEAST_BLUEPRINT_ID) REFERENCES BEAST_BLUEPRINT (ID);

--changeset Jiri.Kriz1:1576501454269-49
ALTER TABLE BEAST_VULNERABILITY ADD CONSTRAINT BEAST_VULNERABILITY_BEAST_BLUEPRINT_ID_FK FOREIGN KEY (BEAST_BLUEPRINT_ID) REFERENCES BEAST_BLUEPRINT (ID);

--changeset Jiri.Kriz1:1576501454269-50
ALTER TABLE COHERENCE ADD CONSTRAINT COHERENCE_PERSON_ID_FK FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID);

--changeset Jiri.Kriz1:1576501454269-51
ALTER TABLE COHERENCE ADD CONSTRAINT COHERENCE_PROFESSION_KNOWHOW_ID_FK FOREIGN KEY (WARRIOR_KNOWHOW_ID) REFERENCES PROFESSION_KNOWHOW (ID);

--changeset Jiri.Kriz1:1576501454269-52
ALTER TABLE ENCOUNTER ADD CONSTRAINT ENCOUNTER_BEAST_BLUEPRINT_ID_FK FOREIGN KEY (BEAST_BLUEPRINT_ID) REFERENCES BEAST_BLUEPRINT (ID);

--changeset Jiri.Kriz1:1576501454269-53
ALTER TABLE ENCOUNTER ADD CONSTRAINT ENCOUNTER_PROFESSION_KNOWHOW_ID_FK FOREIGN KEY (WARRIOR_KNOWHOW_ID) REFERENCES PROFESSION_KNOWHOW (ID);

--changeset Jiri.Kriz1:1576501454269-54
ALTER TABLE EQUIPMENT ADD CONSTRAINT EQUIPMENT_STORAGE_UNIT_ID_FK FOREIGN KEY (STORAGE_UNIT_ID) REFERENCES STORAGE_UNIT (ID);

--changeset Jiri.Kriz1:1576501454269-55
ALTER TABLE LOCAL_PRICE ADD CONSTRAINT LOCAL_PRICE_SHOP_ITEM_ID_FK FOREIGN KEY (SHOP_ITEM_ID) REFERENCES SHOP_ITEM (ID);

--changeset Jiri.Kriz1:1576501454269-56
ALTER TABLE PERSON_BLUEPRINT ADD CONSTRAINT PERSON_BLUEPRINT_INVENTORY_ID_FK FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY (ID);

--changeset Jiri.Kriz1:1576501454269-57
ALTER TABLE PERSON ADD CONSTRAINT PERSON_INVENTORY_ID_FK FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY (ID);

--changeset Jiri.Kriz1:1576501454269-58
ALTER TABLE PERSON ADD CONSTRAINT PERSON_PERSON_BLUEPRINT_ID_FK FOREIGN KEY (PERSONBLUEPRINT_ID) REFERENCES PERSON_BLUEPRINT (ID);

--changeset Jiri.Kriz1:1576501454269-59
ALTER TABLE PERSON ADD CONSTRAINT PERSON_RACE_ID_FK FOREIGN KEY (RACE_ID) REFERENCES RACE (ID);

--changeset Jiri.Kriz1:1576501454269-60
ALTER TABLE RACE ADD CONSTRAINT RACE_WEAPONRY_ID_FK FOREIGN KEY (WEAPON_ID) REFERENCES WEAPON (ID);

--changeset Jiri.Kriz1:1576501454269-61
ALTER TABLE SPELLBOOK ADD CONSTRAINT SPELLBOOK_PROFESSION_KNOWHOW_ID_FK FOREIGN KEY (WIZARD_KNOWHOW_ID) REFERENCES PROFESSION_KNOWHOW (ID);

--changeset Jiri.Kriz1:1576501454269-62
ALTER TABLE SPELLBOOK ADD CONSTRAINT SPELLBOOK_SPELL_ID_FK FOREIGN KEY (SPELL_ID) REFERENCES SPELL (ID);

--changeset Jiri.Kriz1:1576501454269-63
ALTER TABLE STORAGE_UNIT ADD CONSTRAINT STORAGE_UNIT_EQUIPMENT_ID_FK FOREIGN KEY (ID) REFERENCES EQUIPMENT (ID);

--changeset Jiri.Kriz1:1576501454269-64
ALTER TABLE STORAGE_UNIT ADD CONSTRAINT STORAGE_UNIT_INVENTORY_ID_FK FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY (ID);

--changeset Jiri.Kriz1:1576501454269-65
ALTER TABLE TREASURE_BLUEPRINT ADD CONSTRAINT TREASURE_BLUEPRINT_GEMSTONE_ID_FK FOREIGN KEY (GEMSTONE_ID) REFERENCES GEMSTONE (ID);

--changeset Jiri.Kriz1:1576501454269-66
ALTER TABLE WEAPONTYPE_PROFICIENCY ADD CONSTRAINT WEAPONTYPE_PROFICIENCY_PROFESSION_KNOWHOW_ID_FK FOREIGN KEY (WARRIOR_KNOWHOW_ID) REFERENCES PROFESSION_KNOWHOW (ID);

--changeset Jiri.Kriz1:1576501454269-67
ALTER TABLE WEAPONTYPE_PROFICIENCY ADD CONSTRAINT WEAPONTYPE_PROFICIENCY_WEAPON_BLUEPRINT_ID_FK FOREIGN KEY (WEAPON_BLUEPRINT_ID) REFERENCES WEAPON_BLUEPRINT (ID);

--changeset Jiri.Kriz1:1576501454269-68
ALTER TABLE WEAPON ADD CONSTRAINT WEAPON_EQUIPMENT_ID_FK FOREIGN KEY (ID) REFERENCES EQUIPMENT (ID);

--changeset Jiri.Kriz1:1576501454269-69
ALTER TABLE WEAPON_PROFICIENCY ADD CONSTRAINT WEAPON_PROFICIENCY_PROFESSION_KNOWHOW_ID_FK FOREIGN KEY (WARRIOR_KNOWHOW_ID) REFERENCES PROFESSION_KNOWHOW (ID);

--changeset Jiri.Kriz1:1576501454269-70
ALTER TABLE WEAPON_PROFICIENCY ADD CONSTRAINT WEAPON_PROFICIENCY_WEAPON_ID_FK FOREIGN KEY (WEAPON_ID) REFERENCES WEAPON (ID);

--changeset Jiri.Kriz1:1576501454269-71
ALTER TABLE WEAPON_TYPE ADD CONSTRAINT WEAPON_TYPE_WEAPON_ID_FK FOREIGN KEY (WEAPON_ID) REFERENCES WEAPON (ID);

--changeset Jan.Zatloukal:1576501454269-72
ALTER TABLE SHOP_ITEM ADD BLUEPRINT_ID RAW(16) NOT NULL ;

--changeset Jan.Zatloukal:1576501454269-73
alter table TREASURE_BLUEPRINT add POLISHED NUMBER(1);

--changeset Jan.Zatloukal:1576501454269-74
alter table TREASURE_BLUEPRINT drop column STONE;

--changeset Jan.Zatloukal:1576501454269-75
alter table TREASURE_BLUEPRINT rename column METAL to MATERIAL;

--changeset Jan.Zatloukal:1576501454269-76
alter table TREASURE_BLUEPRINT rename column METAL_WEIGHT to MATERIAL_WEIGHT;

